"use client";
import { getApiUrl, getAuthHeaders } from "@/utils/api";


import { useState, useEffect } from "react";
import { BookOpen, CheckCircle2, Award, Clock, ArrowRight, HelpCircle } from "lucide-react";
import { LearningPath, LearningLesson } from "@/types";

const FALLBACK_PATHS: LearningPath[] = [
  {
    id: 1,
    title: "Carbon Footprint Foundations",
    description: "Learn the basics of greenhouse gases, global emissions targets, and carbon accounting.",
    difficulty: "Beginner",
    estimated_minutes: 15,
    xp_reward: 150,
    lessons: [
      {
        id: 101,
        path_id: 1,
        title: "What is Carbon Footprint?",
        content: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by human actions. The global average carbon footprint is roughly 4.7 tons of CO2e per person. To prevent planetary temperatures from rising beyond 1.5C over pre-industrial levels, the global annual average needs to drop under 2.0 tons per person by 2050. Every activity from commuting to streaming contributes.",
        quiz_question: "What is the targeted global average carbon footprint per person by 2050 to avoid critical heating?",
        quiz_options: ["Under 2.0 tons", "Under 10.0 tons", "Exactly 5.0 tons", "No limit"],
        quiz_answer: "Under 2.0 tons",
        xp_reward: 50
      },
      {
        id: 102,
        path_id: 1,
        title: "Understanding CO2 equivalents (CO2e)",
        content: "Different greenhouse gases trap heat differently. Methane (CH4) is over 28 times more potent than carbon dioxide (CO2) over a 100-year timescale, while nitrous oxide (N2O) is 265 times more potent. To simplify measurements, all gases are converted to CO2 equivalents (CO2e), expressing the footprint in terms of the amount of CO2 that would cause equal global warming.",
        quiz_question: "What does the abbreviation 'CO2e' stand for in carbon tracking?",
        quiz_options: ["Carbon Dioxide equivalent", "Carbon Oxygen emission", "Combined Organic elements", "Carbonic Energy standard"],
        quiz_answer: "Carbon Dioxide equivalent",
        xp_reward: 50
      }
    ]
  },
  {
    id: 2,
    title: "Sustainable Consumption & Diet",
    description: "Understand the massive carbon impact of what you eat and consume.",
    difficulty: "Intermediate",
    estimated_minutes: 20,
    xp_reward: 200,
    lessons: [
      {
        id: 201,
        path_id: 2,
        title: "The Methane Footprint of Red Meat",
        content: "Animal agriculture contributes around 14.5% of all global greenhouse emissions. Ruminant animals like cows and sheep produce methane through enteric fermentation during digestion. 1 kg of beef produces roughly 27 kg of CO2e, whereas 1 kg of tofu or vegetables produces under 1.5 kg. Swapping beef for beans or vegan options twice a week decreases your dietary footprint by over 30%.",
        quiz_question: "Why is red meat (like beef) far more carbon-intensive than plant protein?",
        quiz_options: [
          "Cows produce methane during digestion",
          "Vegetables are artificial and do not breathe",
          "Vegetables require heating to grow",
          "Red meat is processed using coal furnaces"
        ],
        quiz_answer: "Cows produce methane during digestion",
        xp_reward: 50
      }
    ]
  }
];

export default function Education() {
  const [paths, setPaths] = useState<LearningPath[]>(FALLBACK_PATHS);
  const [selectedPath, setSelectedPath] = useState<LearningPath>(FALLBACK_PATHS[0]);
  const [selectedLesson, setSelectedLesson] = useState<LearningLesson>(FALLBACK_PATHS[0].lessons[0]);
  const [selectedAnswer, setSelectedAnswer] = useState("");
  const [quizResult, setQuizResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [completedLessons, setCompletedLessons] = useState<number[]>([]);

  useEffect(() => {
    const fetchPaths = async () => {
      try {
        const res = await fetch(`${getApiUrl()}/api/education/paths`, {
          headers: getAuthHeaders()
        });
        if (res.ok) {
          const data: LearningPath[] = await res.json();
          setPaths(data);
          setSelectedPath(data[0]);
          setSelectedLesson(data[0].lessons[0]);
        }
      } catch (err) {
        console.log("Using localized courseware modules.");
      }
    };
    fetchPaths();
  }, []);

  const handleSelectLesson = (lesson: LearningLesson) => {
    setSelectedLesson(lesson);
    setSelectedAnswer("");
    setQuizResult(null);
  };

  const handleSelectPath = (path: LearningPath) => {
    setSelectedPath(path);
    setSelectedLesson(path.lessons[0]);
    setSelectedAnswer("");
    setQuizResult(null);
  };

  const handleSubmitQuiz = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedAnswer) return;

    setLoading(true);

    try {
      const res = await fetch(`${getApiUrl()}/api/education/lessons/${selectedLesson.id}/quiz`, {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
          ...getAuthHeaders()
        },
        body: JSON.stringify({ answer: selectedAnswer })
      });

      if (res.ok) {
        const data = await res.json();
        setQuizResult(data);
        if (data.correct) {
          setCompletedLessons(prev => [...prev, selectedLesson.id]);
        }
      } else {
        const isCorrect = selectedAnswer === selectedLesson.quiz_answer;
        setQuizResult({
          correct: isCorrect,
          xp_earned: isCorrect ? selectedLesson.xp_reward : 0,
          explanation: isCorrect 
            ? `Correct! You earned {selectedLesson.xp_reward} XP. ${selectedLesson.quiz_answer} is the right answer.`
            : "Incorrect answer. Try reading the lesson text again to identify the correct response."
        });
        if (isCorrect) {
          setCompletedLessons(prev => [...prev, selectedLesson.id]);
        }
      }
    } catch {
      const isCorrect = selectedAnswer === selectedLesson.quiz_answer;
      setQuizResult({
        correct: isCorrect,
        xp_earned: isCorrect ? selectedLesson.xp_reward : 0,
        explanation: isCorrect 
          ? `Correct! You earned ${selectedLesson.xp_reward} XP. ${selectedLesson.quiz_answer} is the right answer.`
          : "Incorrect answer. Try reading the lesson text again to identify the correct response."
      });
      if (isCorrect) {
        setCompletedLessons(prev => [...prev, selectedLesson.id]);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col gap-10 py-6">
      
      {/* Header */}
      <div>
        <h1 className="font-heading text-3xl font-extrabold text-gray-900 dark:text-white">Education Center</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Acquire climate science knowledge, complete lesson quizzes, and accumulate green credentials</p>
      </div>

      <div className="grid gap-8 lg:grid-cols-4">
        {/* Left Column: Path & Lesson list */}
        <div className="lg:col-span-1 flex flex-col gap-6">
          {/* Paths selector */}
          <div className="flex flex-col gap-2">
            <span className="text-xs font-semibold uppercase text-gray-400 tracking-wider">Courses</span>
            <div className="flex flex-col gap-2">
              {paths.map((p) => (
                <button
                  key={p.id}
                  onClick={() => handleSelectPath(p)}
                  className={`p-3 rounded-xl border text-left transition-colors text-xs ${
                    selectedPath.id === p.id 
                      ? "bg-brand-emerald/10 border-brand-emerald text-brand-emerald font-bold" 
                      : "glass-card text-gray-700 dark:text-gray-300 hover:border-brand-emerald/40"
                  }`}
                >
                  <span className="block truncate">{p.title}</span>
                  <div className="flex justify-between mt-1 text-[10px] text-gray-400">
                    <span>{p.difficulty}</span>
                    <span>{p.estimated_minutes} mins</span>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Lessons list inside selected path */}
          <div className="flex flex-col gap-2">
            <span className="text-xs font-semibold uppercase text-gray-400 tracking-wider">Lessons</span>
            <div className="flex flex-col gap-2">
              {selectedPath.lessons?.map((les) => {
                const isCompleted = completedLessons.includes(les.id);
                const isSelected = selectedLesson.id === les.id;
                return (
                  <button
                    key={les.id}
                    onClick={() => handleSelectLesson(les)}
                    className={`p-3 rounded-xl border text-left text-xs transition-colors flex items-center justify-between ${
                      isSelected 
                        ? "bg-brand-sky/10 border-brand-sky text-brand-sky font-bold" 
                        : "glass-card text-gray-700 dark:text-gray-300 hover:border-brand-sky/40"
                    }`}
                  >
                    <span className="truncate pr-2">{les.title}</span>
                    {isCompleted ? (
                      <CheckCircle2 className="h-4 w-4 text-brand-emerald" />
                    ) : (
                      <ArrowRight className="h-3.5 w-3.5 text-gray-400" />
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right Columns: Lesson content & Quiz */}
        <div className="lg:col-span-3 flex flex-col gap-6">
          {selectedLesson ? (
            <div className="glass-card rounded-3xl p-6 border border-white/20 flex flex-col gap-6">
              
              {/* Content Header */}
              <div className="border-b border-gray-100 dark:border-brand-borderDark pb-4">
                <div className="flex justify-between items-start gap-4">
                  <h2 className="text-xl font-bold text-gray-800 dark:text-white">{selectedLesson.title}</h2>
                  <div className="flex gap-3 text-[10px] font-semibold text-brand-emerald">
                    <span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5" /> 5 mins</span>
                    <span className="flex items-center gap-1"><Award className="h-3.5 w-3.5" /> +{selectedLesson.xp_reward} XP</span>
                  </div>
                </div>
              </div>

              {/* Lesson Text */}
              <div className="text-sm leading-relaxed text-gray-600 dark:text-gray-300">
                {selectedLesson.content}
              </div>

              {/* Quiz section */}
              {selectedLesson.quiz_question && (
                <div className="border-t border-gray-100 dark:border-brand-borderDark pt-6 flex flex-col gap-4">
                  <div className="flex items-center gap-1.5 text-brand-sky">
                    <HelpCircle className="h-4 w-4" />
                    <span className="text-xs font-bold uppercase tracking-wider">Lesson Review Quiz</span>
                  </div>

                  <form onSubmit={handleSubmitQuiz} className="flex flex-col gap-4">
                    <span className="text-sm font-bold text-gray-800 dark:text-white">{selectedLesson.quiz_question}</span>
                    
                    <div className="flex flex-col gap-2">
                      {selectedLesson.quiz_options?.map((opt) => {
                        const isChecked = selectedAnswer === opt;
                        return (
                          <label
                            key={opt}
                            className={`flex items-center gap-3 p-3.5 rounded-xl border text-xs cursor-pointer transition-colors ${
                              isChecked 
                                ? "bg-brand-sky/5 border-brand-sky text-brand-sky font-semibold" 
                                : "glass-card text-gray-700 dark:text-gray-300 hover:border-brand-sky/20"
                            }`}
                          >
                            <input
                              type="radio"
                              name="quiz-opt"
                              value={opt}
                              checked={isChecked}
                              onChange={() => {
                                setSelectedAnswer(opt);
                                setQuizResult(null);
                              }}
                              className="h-4 w-4 text-brand-sky focus:ring-brand-sky accent-brand-sky cursor-pointer"
                              required
                            />
                            <span>{opt}</span>
                          </label>
                        );
                      })}
                    </div>

                    <button
                      type="submit"
                      disabled={loading || !selectedAnswer}
                      className="bg-brand-emerald hover:bg-brand-forest text-white font-semibold py-2.5 rounded-xl transition-colors disabled:opacity-50 text-xs mt-2"
                    >
                      {loading ? (
                        <span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent inline-block" />
                      ) : (
                        <span>Verify Answer & Claim XP</span>
                      )}
                    </button>
                  </form>

                  {/* Results box */}
                  {quizResult && (
                    <div className={`p-4 border rounded-xl text-xs leading-relaxed animate-in fade-in duration-200 ${
                      quizResult.correct 
                        ? "bg-brand-emerald/10 border-brand-emerald/30 text-brand-emerald" 
                        : "bg-red-500/10 border-red-500/20 text-red-500"
                    }`}>
                      <span className="block font-bold mb-1">{quizResult.correct ? "Excellent Work!" : "Try Again"}</span>
                      {quizResult.explanation}
                    </div>
                  )}
                </div>
              )}
            </div>
          ) : (
            <div className="glass-card rounded-3xl p-8 text-center text-gray-400">
              <BookOpen className="h-8 w-8 mx-auto mb-2 text-gray-500" />
              <span>Select a lesson from the left column to begin courseware study.</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
