import pytest
from fastapi.testclient import TestClient
from tests.conftest import get_auth_headers

def test_predict_forecast(client: TestClient):
    headers = get_auth_headers(client, "forecast_user@carboeco.org")
    response = client.get("/api/ai/predict/forecast", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "forecast" in data
    assert len(data["forecast"]) == 12
    assert "months" in data
    assert "feature_importance" in data

def test_predict_risk(client: TestClient):
    headers = get_auth_headers(client, "risk_user@carboeco.org")
    response = client.get("/api/ai/predict/risk", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "goal_probability" in data
    assert "risk_behaviors" in data
    assert len(data["risk_behaviors"]) >= 1

def test_coach_chat(client: TestClient):
    headers = get_auth_headers(client, "coach_user@carboeco.org")
    
    # Send specific keyword query
    response = client.post(
        "/api/ai/coach/chat",
        headers=headers,
        json={"message": "What is my carbon footprint?"}
    )
    assert response.status_code == 200
    data = response.json()
    assert "reply" in data
    assert "greenhouse gases" in data.get("reply").lower()

    # Send general fallback query
    response2 = client.post(
        "/api/ai/coach/chat",
        headers=headers,
        json={"message": "Hello Sustainability Coach!"}
    )
    assert response2.status_code == 200
    assert "reply" in response2.json()

def test_coach_challenges(client: TestClient):
    headers = get_auth_headers(client, "challenge_user@carboeco.org")
    response = client.get("/api/ai/coach/challenges", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert len(data) == 3
    assert "title" in data[0]
    assert "xp" in data[0]

def test_copilot_roadmap(client: TestClient):
    headers = get_auth_headers(client, "roadmap_user@carboeco.org")
    response = client.post("/api/ai/copilot/roadmap", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "steps" in data
    assert len(data["steps"]) == 4
    assert "total_projected_savings_annual_kg" in data

def test_digital_twin_state(client: TestClient):
    headers = get_auth_headers(client, "twin_user@carboeco.org")
    response = client.get("/api/ai/digital-twin", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "tree_growth_stage" in data
    assert "energy_efficiency_score" in data
    assert "current_avatar_state_json" in data

def test_coach_chat_gemini_active(client: TestClient):
    from unittest.mock import MagicMock, patch
    with patch("app.services.sustainability_coach.genai") as mock_genai, \
         patch("app.services.sustainability_coach.settings") as mock_settings:
        
        mock_settings.GEMINI_API_KEY = "test-key"
        
        mock_client = MagicMock()
        mock_genai.Client.return_value = mock_client
        
        mock_response = MagicMock()
        mock_response.text = "This is a response generated by mock Gemini."
        mock_client.models.generate_content.return_value = mock_response
        
        headers = get_auth_headers(client, "coach_gemini_user@carboeco.org")
        response = client.post(
            "/api/ai/coach/chat",
            headers=headers,
            json={"message": "Any message"}
        )
        assert response.status_code == 200
        data = response.json()
        assert data["reply"] == "This is a response generated by mock Gemini."
        mock_client.models.generate_content.assert_called_once()

def test_coach_challenges_gemini_active(client: TestClient):
    from unittest.mock import MagicMock, patch
    with patch("app.services.sustainability_coach.genai") as mock_genai, \
         patch("app.services.sustainability_coach.settings") as mock_settings:
        
        mock_settings.GEMINI_API_KEY = "test-key"
        
        mock_client = MagicMock()
        mock_genai.Client.return_value = mock_client
        
        mock_response = MagicMock()
        mock_challenge_1 = MagicMock()
        mock_challenge_1.title = "Gemini Challenge 1"
        mock_challenge_1.description = "Save some CO2 with Gemini"
        mock_challenge_1.xp = 120
        mock_challenge_1.co2_saving = 15.5
        
        mock_challenge_list = MagicMock()
        mock_challenge_list.challenges = [mock_challenge_1]
        mock_response.parsed = mock_challenge_list
        
        mock_client.models.generate_content.return_value = mock_response
        
        headers = get_auth_headers(client, "challenge_gemini_user@carboeco.org")
        response = client.get("/api/ai/coach/challenges", headers=headers)
        assert response.status_code == 200
        data = response.json()
        assert len(data) == 1
        assert data[0]["title"] == "Gemini Challenge 1"
        assert data[0]["xp"] == 120

def test_copilot_roadmap_gemini_active(client: TestClient):
    from unittest.mock import MagicMock, patch
    with patch("app.services.sustainability_coach.genai") as mock_genai, \
         patch("app.services.sustainability_coach.settings") as mock_settings:
        
        mock_settings.GEMINI_API_KEY = "test-key"
        
        mock_client = MagicMock()
        mock_genai.Client.return_value = mock_client
        
        mock_response = MagicMock()
        mock_step = MagicMock()
        mock_step.phase = "Gemini Phase 1"
        mock_step.actions = ["Use solar energy", "Plant a tree"]
        mock_step.projected_co2_savings_kg = 50.0
        mock_step.difficulty = "Easy"
        
        mock_roadmap = MagicMock()
        mock_roadmap.steps = [mock_step]
        mock_roadmap.total_projected_savings_annual_kg = 200.0
        mock_response.parsed = mock_roadmap
        
        mock_client.models.generate_content.return_value = mock_response
        
        headers = get_auth_headers(client, "roadmap_gemini_user@carboeco.org")
        response = client.post("/api/ai/copilot/roadmap", headers=headers)
        assert response.status_code == 200
        data = response.json()
        assert data["total_projected_savings_annual_kg"] == 200.0
        assert data["steps"][0]["phase"] == "Gemini Phase 1"

def test_scan_image_fallback(client: TestClient):
    headers = get_auth_headers(client, "scan_fallback_user@carboeco.org")
    response = client.post(
        "/api/ai/scan",
        headers=headers,
        json={"image_base64": "data:image/jpeg;base64,ZHVtbXlfaW1hZ2VfZGF0YQ=="}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["category"] == "food"
    assert data["subcategory"] == "vegan"
    assert data["value"] == 1.5
    assert "サラダ" in data["explanation"] or "salad" in data["explanation"].lower()

def test_scan_image_gemini_active(client: TestClient):
    from unittest.mock import MagicMock, patch
    with patch("app.services.sustainability_coach.genai") as mock_genai, \
         patch("app.services.sustainability_coach.types") as mock_types, \
         patch("app.services.sustainability_coach.settings") as mock_settings:
        
        mock_settings.GEMINI_API_KEY = "test-key"
        
        mock_client = MagicMock()
        mock_genai.Client.return_value = mock_client
        
        mock_response = MagicMock()
        mock_scan_result = MagicMock()
        mock_scan_result.category = "energy"
        mock_scan_result.subcategory = "electricity"
        mock_scan_result.value = 150.0
        mock_scan_result.unit = "kWh"
        mock_scan_result.explanation = "Detected 150 kWh from mock utility bill."
        mock_response.parsed = mock_scan_result
        
        mock_client.models.generate_content.return_value = mock_response
        
        headers = get_auth_headers(client, "scan_gemini_user@carboeco.org")
        response = client.post(
            "/api/ai/scan",
            headers=headers,
            json={"image_base64": "data:image/jpeg;base64,ZHVtbXlfaW1hZ2VfZGF0YQ=="}
        )
        assert response.status_code == 200
        data = response.json()
        assert data["category"] == "energy"
        assert data["subcategory"] == "electricity"
        assert data["value"] == 150.0
        assert data["unit"] == "kWh"
        assert "150 kWh" in data["explanation"]
