import { describe, it, expect, vi } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import React from "react";
import Education from "@/app/education/page";

const MOCK_PATHS = [
  {
    id: 1,
    title: "Carbon Footprint Foundations",
    description: "Learn the basics of greenhouse gases, global emissions targets, and carbon accounting.",
    difficulty: "Beginner",
    estimated_minutes: 15,
    xp_reward: 150,
    lessons: [
      {
        id: 101,
        path_id: 1,
        title: "What is Carbon Footprint?",
        content: "A carbon footprint is the total amount of greenhouse gases generated by human actions.",
        quiz_question: "What is the targeted global average carbon footprint per person by 2050 to avoid critical heating?",
        quiz_options: ["Under 2.0 tons", "Under 10.0 tons", "Exactly 5.0 tons", "No limit"],
        quiz_answer: "Under 2.0 tons",
        xp_reward: 50
      },
      {
        id: 102,
        path_id: 1,
        title: "Understanding CO2 equivalents (CO2e)",
        content: "Different greenhouse gases trap heat differently.",
        quiz_question: "What does the abbreviation 'CO2e' stand for in carbon tracking?",
        quiz_options: ["Carbon Dioxide equivalent", "Carbon Oxygen emission", "Combined Organic elements", "Carbonic Energy standard"],
        quiz_answer: "Carbon Dioxide equivalent",
        xp_reward: 50
      }
    ]
  }
];

describe("Education page component", () => {
  it("renders course pathways and lessons lists", async () => {
    global.fetch = vi.fn().mockImplementation((url) => {
      if (url.includes("/api/education/paths")) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(MOCK_PATHS)
        });
      }
      return Promise.reject(new Error("Unknown URL"));
    });

    render(<Education />);
    expect(screen.getByRole("heading", { name: /education center/i })).toBeInTheDocument();
    
    await screen.findByText("Carbon Footprint Foundations");
    const lessonItems = screen.getAllByText("What is Carbon Footprint?");
    expect(lessonItems.length).toBeGreaterThan(0);
  });

  it("renders selected lesson text details", async () => {
    global.fetch = vi.fn().mockImplementation((url) => {
      if (url.includes("/api/education/paths")) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(MOCK_PATHS)
        });
      }
      return Promise.reject(new Error("Unknown URL"));
    });

    render(<Education />);
    
    await screen.findByText("Carbon Footprint Foundations");
    expect(screen.getByRole("heading", { name: "What is Carbon Footprint?" })).toBeInTheDocument();
    expect(screen.getByText(/total amount of greenhouse gases generated/i)).toBeInTheDocument();
  });

  it("handles course selection and switches lessons", async () => {
    global.fetch = vi.fn().mockImplementation((url) => {
      if (url.includes("/api/education/paths")) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(MOCK_PATHS)
        });
      }
      return Promise.reject(new Error("Unknown URL"));
    });

    render(<Education />);
    
    await screen.findByText("Carbon Footprint Foundations");
    
    const nextLessonBtn = screen.getByRole("button", { name: /understanding co2 equivalents/i });
    fireEvent.click(nextLessonBtn);
    
    await waitFor(() => {
      expect(screen.getByRole("heading", { name: "Understanding CO2 equivalents (CO2e)" })).toBeInTheDocument();
    });
  });

  it("submits quiz answer and displays score/status feedback", async () => {
    global.fetch = vi.fn().mockImplementation((url) => {
      if (url.includes("/api/education/paths")) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(MOCK_PATHS)
        });
      }
      if (url.includes("/quiz")) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({
            correct: true,
            xp_earned: 50,
            explanation: "Correct! You earned 50 XP. Under 2.0 tons is the right answer."
          })
        });
      }
      return Promise.reject(new Error("Unknown URL"));
    });

    render(<Education />);
    
    await screen.findByText("Carbon Footprint Foundations");
    
    const radioInput = screen.getByDisplayValue("Under 2.0 tons");
    fireEvent.click(radioInput);
    
    const submitBtn = screen.getByRole("button", { name: /verify answer & claim xp/i });
    fireEvent.click(submitBtn);

    await waitFor(() => {
      expect(screen.getByText("Excellent Work!")).toBeInTheDocument();
      expect(screen.getByText(/under 2.0 tons is the right answer/i)).toBeInTheDocument();
    });
  });
});
