from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from datetime import datetime, timedelta, timezone
import random
import logging
import base64

from app.models import CarbonLog, UserProfile, AIRecommendation
from app.services.ai_engine import AIEngine
from app.services.carbon_service import CarbonService
from app.config import settings

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None
    types = None

from pydantic import BaseModel, Field

class GeminiScanResult(BaseModel):
    category: str = Field(description="Must be one of: transportation, energy, food, waste, shopping, digital")
    subcategory: str = Field(description="Must match one of the exact subcategories (e.g. petrol_car, electricity, beef, landfill, clothing, streaming, etc.)")
    value: float = Field(description="The numeric consumption value extracted from the image")
    unit: str = Field(description="The unit of measurement (e.g. km, kWh, kg, liters, USD, hours, queries)")
    explanation: str = Field(description="A brief explanation of what was detected and how the carbon footprint was estimated")

class GeminiChallenge(BaseModel):
    title: str
    description: str
    xp: int
    co2_saving: float

class GeminiRoadmapStep(BaseModel):
    phase: str
    actions: list[str]
    projected_co2_savings_kg: float
    difficulty: str

class GeminiRoadmap(BaseModel):
    steps: list[GeminiRoadmapStep]
    total_projected_savings_annual_kg: float

logger = logging.getLogger("carboeco")

class SustainabilityCoach:
    
    Q_AND_A_KNOWLEDGE = {
        "carbon footprint": (
            "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) "
            "generated by our actions. Globally, the average carbon footprint is close to 4 tons per person annually. "
            "To avoid a 2C rise in global temperatures, the average global carbon footprint needs to drop to under 2 tons by 2050."
        ),
        "reduce transport": (
            "You can reduce your transport emissions by walking or biking for short trips (<2 km), using public transit "
            "(metro or buses emit up to 80% less carbon per passenger-kilometer than cars), carpooling, or transitioning "
            "to an Electric Vehicle (EV). Maintaining proper tire pressure and driving smoothly also improves fuel efficiency."
        ),
        "reduce food": (
            "Food represents about 10-30% of a household's carbon footprint. Red meat (beef and lamb) is particularly "
            "carbon-intensive, generating up to 27 kg of CO2e per kg. Eating plant-based meals twice a week, reducing food waste, "
            "and buying local/seasonal produce are highly effective ways to lower food footprint."
        ),
        "solar panels": (
            "Installing solar photovoltaic (PV) panels is a major long-term carbon reducer. On average, a standard home "
            "solar system can offset about 3 to 4 tons of carbon dioxide per year—roughly equivalent to planting 100 trees "
            "annually. It typically pays for itself in utility savings within 7 to 9 years."
        ),
        "electricity": (
            "Lower your home electricity footprint by switching to LED lightbulbs (uses 75% less energy), using smart power strips "
            "to prevent 'vampire load', setting thermostats to 68F (20C) in winter and 78F (25C) in summer, and buying Energy "
            "Star-certified appliances."
        ),
        "digital footprint": (
            "While invisible, the digital world is energy-hungry. Streaming in Standard Definition (SD) instead of 4K, "
            "cleaning out old cloud storage, using search engines that plant trees, and shutting down devices overnight "
            "collectively reduce the carbon footprint of data centers."
        ),
        "offset": (
            "Carbon offsets let you fund projects that reduce greenhouse gases—like reforestation, wind farms, or methane captures—"
            "to balance out your own unavoidable emissions. While helpful, offsetting should only be used after you have "
            "maximized your direct emission reductions."
        )
    }

    @classmethod
    async def get_coach_response(cls, db: AsyncSession, user_id: int, query: str) -> str:
        """
        Uses Gemini API to generate personalized sustainability response with RAG context
        comprising user logs history, regional parameters, and risk profiles.
        Falls back to local QA mapping if the Gemini key is unconfigured.
        """
        # Fetch user profile and emissions context for RAG prompt personalization
        stmt_prof = select(UserProfile).where(UserProfile.user_id == user_id)
        res_prof = await db.execute(stmt_prof)
        profile = res_prof.scalar_one_or_none()
        budget = profile.carbon_budget if profile else 15.0
        region = profile.region if profile else "US"

        # Calculate user risk and goal probabilities
        analysis = await AIEngine.calculate_risk_and_goal_probability(db, user_id)
        risks = analysis.get("risk_behaviors", [])
        daily_mean = analysis.get("daily_mean", 0.0)

        rag_context = (
            f"[User RAG context]\n"
            f"- User Region: {region}\n"
            f"- Current Daily Footprint Mean: {daily_mean:.2f} kg CO2e\n"
            f"- Daily Target Budget: {budget:.2f} kg CO2e\n"
            f"- Goal Achievement Probability: {analysis.get('goal_probability', 0.5) * 100:.0f}%\n"
            f"- High Risk Behaviors Detected: {', '.join(risks)}\n"
        )

        if genai and settings.GEMINI_API_KEY:
            try:
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                prompt = (
                    "You are the CarboECO Sustainability Coach, a senior environmental scientist AI. "
                    "Provide a warm, encouraging, scientifically accurate response to the user's question, "
                    "referencing the user's real carbon tracking metrics and risks if relevant.\n\n"
                    f"{rag_context}\n"
                    f"User Question: {query}\n"
                    "Keep your response concise, engaging, and under 150 words."
                )
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=prompt
                )
                if response and response.text:
                    return response.text.strip()
            except Exception as e:
                logger.error(f"Error calling Gemini in get_coach_response: {e}")

        # Local fallback with RAG personalization enrichment
        q = query.lower()
        for key, response in cls.Q_AND_A_KNOWLEDGE.items():
            if key in q:
                return response
        
        risk_str = risks[0] if risks else "Keep tracking your carbon inputs daily."
        return (
            f"Based on your profile in region {region} (Daily Avg: {daily_mean:.1f} kg CO2e vs Budget: {budget} kg): "
            f"Your highest priority is to address this risk: '{risk_str}'. "
            "To reduce your emissions, remember the core sequence: Avoid (e.g. swap private vehicles for public transit), "
            "Reduce (e.g. choose plant-based meals), and Offset (fund verified offset projects via the Marketplace)."
        )

    @classmethod
    async def get_weekly_challenges(cls, db: AsyncSession, user_id: int) -> list[dict]:
        """
        Generates weekly eco-challenges tailored to the user's highest emission category.
        Uses Gemini API structured output if key is configured.
        """
        thirty_days_ago = (datetime.now(timezone.utc) - timedelta(days=30)).strftime("%Y-%m-%d")
        stmt = select(CarbonLog).where(
            CarbonLog.user_id == user_id,
            CarbonLog.date >= thirty_days_ago
        )
        res = await db.execute(stmt)
        logs = res.scalars().all()

        highest_cat = "transportation"
        if logs:
            cat_totals = {}
            for log in logs:
                cat_totals[log.category] = cat_totals.get(log.category, 0) + log.co2_equivalent
            highest_cat = max(cat_totals, key=cat_totals.get)

        if genai and settings.GEMINI_API_KEY:
            try:
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                
                class GeminiChallengeList(BaseModel):
                    challenges: list[GeminiChallenge]

                prompt = (
                    f"Generate 3 weekly eco-challenges for a user whose highest carbon footprint category is '{highest_cat}'. "
                    "Provide 2 challenges from this highest category, and 1 challenge from another carbon category (like food, energy, waste, digital, or shopping). "
                    "Make sure the challenges are realistic, actionable, and fun. "
                    "Assign a reasonable experience points value (XP, between 30 and 150) and estimated CO2 savings in kg (between 0.5 and 25.0)."
                )

                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": GeminiChallengeList
                    }
                )
                if response and response.parsed:
                    return [
                        {
                            "title": ch.title,
                            "description": ch.description,
                            "xp": ch.xp,
                            "co2_saving": ch.co2_saving
                        }
                        for ch in response.parsed.challenges
                    ]
            except Exception as e:
                logger.error(f"Error calling Gemini in get_weekly_challenges: {e}")

        # Fallback database challenges
        challenges = {
            "transportation": [
                {"title": "Transit Trial", "description": "Take the metro or bus for 3 commutes instead of driving.", "xp": 80, "co2_saving": 12.5},
                {"title": "Eco-Pedaling", "description": "Walk or bike for all trips under 2 km this week.", "xp": 100, "co2_saving": 8.0},
                {"title": "Carpool Coordinator", "description": "Share a ride to work or event with a colleague.", "xp": 60, "co2_saving": 10.2}
            ],
            "energy": [
                {"title": "Vampire Slayer", "description": "Unplug all electronics and chargers not in use before bed.", "xp": 50, "co2_saving": 4.5},
                {"title": "Cold Clean", "description": "Wash all laundry cycles in cold water instead of hot.", "xp": 60, "co2_saving": 3.8},
                {"title": "Thermostat Tweak", "description": "Adjust your heating down 1 degree or cooling up 1 degree for the week.", "xp": 70, "co2_saving": 9.0}
            ],
            "food": [
                {"title": "Meatless Mondays", "description": "Prepare fully vegetarian meals for the entire day.", "xp": 60, "co2_saving": 6.4},
                {"title": "Go Vegan for 2 Days", "description": "Eat purely plant-based meals for 48 hours.", "xp": 100, "co2_saving": 14.2},
                {"title": "Zero Waste Chef", "description": "Throw away absolutely zero edible food leftovers this week.", "xp": 80, "co2_saving": 5.0}
            ],
            "waste": [
                {"title": "Sorting Champion", "description": "Clean and sort all plastics, papers, and glass for recycling.", "xp": 50, "co2_saving": 2.2},
                {"title": "Single-Use Strike", "description": "Refuse all single-use plastic cups, straws, and bags for 7 days.", "xp": 80, "co2_saving": 3.5},
                {"title": "Kitchen Composter", "description": "Compost all vegetable peels and organic coffee grounds.", "xp": 70, "co2_saving": 4.0}
            ],
            "shopping": [
                {"title": "Thrift Searcher", "description": "Buy a pre-owned clothing item instead of buying new.", "xp": 70, "co2_saving": 15.0},
                {"title": "No-Buy Challenge", "description": "Commit to buying zero non-essential items for 5 days.", "xp": 90, "co2_saving": 20.0}
            ],
            "digital": [
                {"title": "Digital Detox", "description": "Reduce screen streaming time by 2 hours daily and read a book.", "xp": 60, "co2_saving": 1.5},
                {"title": "Inbox Cleanse", "description": "Delete 100 old emails to clean server capacity storage.", "xp": 50, "co2_saving": 0.8}
            ]
        }

        selected = list(challenges.get(highest_cat, challenges["transportation"]))[:2]
        other_cats = [c for c in challenges.keys() if c != highest_cat]
        random_cat = random.choice(other_cats)
        selected.append(random.choice(challenges[random_cat]))
        return selected

    @classmethod
    async def generate_roadmap(cls, db: AsyncSession, user_id: int) -> dict:
        """
        Creates a custom, multi-step carbon reduction roadmap for the user.
        Injects real-time risk contexts into the Gemini model.
        """
        analysis = await AIEngine.calculate_risk_and_goal_probability(db, user_id)
        risks = analysis.get("risk_behaviors", [])

        # Get user budget & carbon history
        stmt_prof = select(UserProfile).where(UserProfile.user_id == user_id)
        res_prof = await db.execute(stmt_prof)
        profile = res_prof.scalar_one_or_none()
        budget = profile.carbon_budget if profile else 15.0

        thirty_days_ago = (datetime.now(timezone.utc) - timedelta(days=30)).strftime("%Y-%m-%d")
        stmt_logs = select(CarbonLog).where(
            CarbonLog.user_id == user_id,
            CarbonLog.date >= thirty_days_ago
        )
        res_logs = await db.execute(stmt_logs)
        logs = res_logs.scalars().all()

        history_summary = ""
        if logs:
            cat_totals = {}
            for log in logs:
                cat_totals[log.category] = cat_totals.get(log.category, 0) + log.co2_equivalent
            history_summary = ", ".join([f"{cat}: {val:.1f} kg CO2e" for cat, val in cat_totals.items()])
        else:
            history_summary = "No recent logging history."

        if genai and settings.GEMINI_API_KEY:
            try:
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                prompt = (
                    "Generate a custom, 4-phase carbon reduction roadmap for a user.\n"
                    f"User daily carbon budget: {budget} kg CO2e.\n"
                    f"User recent 30-day carbon emissions summary: {history_summary}.\n"
                    f"Identified high-risk behaviors: {', '.join(risks)}.\n\n"
                    "Create a 4-phase pathway:\n"
                    "Phase 1: Immediate Wins (Week 1-2)\n"
                    "Phase 2: Household Adjustments (Month 1)\n"
                    "Phase 3: Systematic Upgrades (Month 3-6)\n"
                    "Phase 4: Structural Changes (Year 1+)\n"
                    "Each phase should contain 3 specific actions. "
                    "Estimate the difficulty (Easy, Medium, Hard) and projected CO2 savings in kg for each phase."
                )

                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": GeminiRoadmap
                    }
                )
                if response and response.parsed:
                    roadmap_data = response.parsed
                    return {
                        "user_id": user_id,
                        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
                        "risk_analysis_context": risks,
                        "steps": [
                            {
                                "phase": step.phase,
                                "actions": step.actions,
                                "projected_co2_savings_kg": step.projected_co2_savings_kg,
                                "difficulty": step.difficulty
                            }
                            for step in roadmap_data.steps
                        ],
                        "total_projected_savings_annual_kg": roadmap_data.total_projected_savings_annual_kg
                    }
            except Exception as e:
                logger.error(f"Error calling Gemini in generate_roadmap: {e}")

        # Local fallback roadmap
        steps = [
            {
                "phase": "Phase 1: Immediate Wins (Week 1-2)",
                "actions": [
                    "Swap short car trips (<3 km) for walking or cycling.",
                    "Eat plant-based meals at least 2 days per week.",
                    "Unplug household standby appliances when not in use."
                ],
                "projected_co2_savings_kg": 25.0,
                "difficulty": "Easy"
            },
            {
                "phase": "Phase 2: Household Adjustments (Month 1)",
                "actions": [
                    "Transition all lightbulbs to Energy Star LEDs.",
                    "Ensure cold-wash settings are selected for laundry.",
                    "Start composting organic kitchen waste."
                ],
                "projected_co2_savings_kg": 60.0,
                "difficulty": "Medium"
            },
            {
                "phase": "Phase 3: Systematic Upgrades (Month 3-6)",
                "actions": [
                    "Upgrade to a smart programmable thermostat.",
                    "For unavoidable long commutes, purchase verified carbon offsets from the Marketplace.",
                    "Transition energy tariff to a 100% green renewable provider."
                ],
                "projected_co2_savings_kg": 180.0,
                "difficulty": "Medium"
            },
            {
                "phase": "Phase 4: Structural Lifestyle Changes (Year 1+)",
                "actions": [
                    "Upgrade your primary vehicle to a battery electric vehicle (EV).",
                    "Install rooftop solar panels or purchase community solar shares.",
                    "Transition heating source from gas to an electric heat pump."
                ],
                "projected_co2_savings_kg": 1200.0,
                "difficulty": "Hard"
            }
        ]

        total_savings = sum(step["projected_co2_savings_kg"] for step in steps)

        return {
            "user_id": user_id,
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
            "risk_analysis_context": risks,
            "steps": steps,
            "total_projected_savings_annual_kg": total_savings
        }

    @staticmethod
    def scan_carbon_image(image_base64: str) -> dict:
        """
        Extracts carbon-relevant activity from an image base64 receipt/bill using Gemini.
        """
        if genai and types and settings.GEMINI_API_KEY:
            try:
                if "," in image_base64:
                    image_base64 = image_base64.split(",")[1]
                
                image_bytes = base64.b64decode(image_base64)
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=[
                        types.Part.from_bytes(
                            data=image_bytes,
                            mime_type="image/jpeg"
                        ),
                        (
                            "Analyze this image. Extract the carbon-relevant activity and categorize it:\n"
                            "- transportation: petrol_car, diesel_car, electric_car, motorcycle, metro, bus, short_flight, long_flight\n"
                            "- energy: electricity, gas, water\n"
                            "- food: beef, pork_poultry, dairy, vegetarian, vegan\n"
                            "- waste: landfill, recycled, composted\n"
                            "- shopping: clothing, electronics, misc\n"
                            "- digital: streaming, browsing, ai_query\n\n"
                            "Return structured JSON matching the response schema."
                        )
                    ],
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": GeminiScanResult
                    }
                )
                if response and response.parsed:
                    return {
                        "category": response.parsed.category,
                        "subcategory": response.parsed.subcategory,
                        "value": response.parsed.value,
                        "unit": response.parsed.unit,
                        "explanation": response.parsed.explanation
                    }
            except Exception as e:
                logger.error(f"Error calling Gemini in scan_carbon_image: {e}")
                
        return {
            "category": "food",
            "subcategory": "vegan",
            "value": 1.5,
            "unit": "kg",
            "explanation": "Offline scanner fallback: Scanned photo detected a vegetarian/vegan meal (~1.5 kg of green salad and tofu)."
        }
