from sqlalchemy.orm import Session
from datetime import datetime, timedelta, timezone
import random
from app.models import CarbonLog, UserProfile, AIRecommendation
from app.services.ai_engine import AIEngine
from app.config import settings
import logging

import base64

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None
    types = None

from pydantic import BaseModel, Field

class GeminiScanResult(BaseModel):
    category: str = Field(description="Must be one of: transportation, energy, food, waste, shopping, digital")
    subcategory: str = Field(description="Must match one of the exact subcategories (e.g. petrol_car, electricity, beef, landfill, clothing, streaming, etc.)")
    value: float = Field(description="The numeric consumption value extracted from the image")
    unit: str = Field(description="The unit of measurement (e.g. km, kWh, kg, liters, USD, hours, queries)")
    explanation: str = Field(description="A brief explanation of what was detected and how the carbon footprint was estimated")

class GeminiChallenge(BaseModel):
    title: str
    description: str
    xp: int
    co2_saving: float

class GeminiRoadmapStep(BaseModel):
    phase: str
    actions: list[str]
    projected_co2_savings_kg: float
    difficulty: str

class GeminiRoadmap(BaseModel):
    steps: list[GeminiRoadmapStep]
    total_projected_savings_annual_kg: float

logger = logging.getLogger("carboeco")

class SustainabilityCoach:
    
    Q_AND_A_KNOWLEDGE = {
        "carbon footprint": (
            "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) "
            "generated by our actions. Globally, the average carbon footprint is close to 4 tons per person annually. "
            "To avoid a 2C rise in global temperatures, the average global carbon footprint needs to drop to under 2 tons by 2050."
        ),
        "reduce transport": (
            "You can reduce your transport emissions by walking or biking for short trips (<2 km), using public transit "
            "(metro or buses emit up to 80% less carbon per passenger-kilometer than cars), carpooling, or transitioning "
            "to an Electric Vehicle (EV). Maintaining proper tire pressure and driving smoothly also improves fuel efficiency."
        ),
        "reduce food": (
            "Food represents about 10-30% of a household's carbon footprint. Red meat (beef and lamb) is particularly "
            "carbon-intensive, generating up to 27 kg of CO2e per kg. Eating plant-based meals twice a week, reducing food waste, "
            "and buying local/seasonal produce are highly effective ways to lower food footprint."
        ),
        "solar panels": (
            "Installing solar photovoltaic (PV) panels is a major long-term carbon reducer. On average, a standard home "
            "solar system can offset about 3 to 4 tons of carbon dioxide per year—roughly equivalent to planting 100 trees "
            "annually. It typically pays for itself in utility savings within 7 to 9 years."
        ),
        "electricity": (
            "Lower your home electricity footprint by switching to LED lightbulbs (uses 75% less energy), using smart power strips "
            "to prevent 'vampire load', setting thermostats to 68F (20C) in winter and 78F (25C) in summer, and buying Energy "
            "Star-certified appliances."
        ),
        "digital footprint": (
            "While invisible, the digital world is energy-hungry. Streaming in Standard Definition (SD) instead of 4K, "
            "cleaning out old cloud storage, using search engines that plant trees, and shutting down devices overnight "
            "collectively reduce the carbon footprint of data centers."
        ),
        "offset": (
            "Carbon offsets let you fund projects that reduce green house gases—like reforestation, wind farms, or methane captures—"
            "to balance out your own unavoidable emissions. While helpful, offsetting should only be used after you have "
            "maximized your direct emission reductions."
        )
    }

    @classmethod
    def get_coach_response(cls, query: str) -> str:
        """
        Simple keyword-based semantic coach response that falls back to a general green coaching script.
        If GEMINI_API_KEY is configured, it uses Gemini API to generate personalized sustainability response.
        """
        if genai and settings.GEMINI_API_KEY:
            try:
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=(
                        "You are the CarboECO Sustainability Coach, an expert environmental assistant. "
                        "Answer the user's question with encouraging, actionable, and scientifically accurate sustainability advice. "
                        "Keep your response concise, engaging, and under 150 words.\n\n"
                        f"User Question: {query}"
                    )
                )
                if response and response.text:
                    return response.text.strip()
            except Exception as e:
                logger.error(f"Error calling Gemini in get_coach_response: {e}")

        # Local fallback logic
        q = query.lower()
        for key, response in cls.Q_AND_A_KNOWLEDGE.items():
            if key in q:
                return response
        
        return (
            "That is an excellent question! Reducing carbon footprint involves three main steps: "
            "1) Measure (which you are doing on CarboECO), 2) Avoid (choosing low-carbon alternatives like metro "
            "and plant-based food), and 3) Offset (funding verified carbon removal projects). For specific guidance, "
            "try asking about 'reduce food', 'reduce transport', 'solar panels', or 'digital footprint'!"
        )

    @staticmethod
    def get_weekly_challenges(db: Session, user_id: int) -> list[dict]:
        """
        Generates weekly eco-challenges tailored to the user's highest emission category.
        If GEMINI_API_KEY is configured, it uses Gemini API structured output to generate custom challenges.
        """
        # Fetch last 30 days logs to see what category is dominant
        thirty_days_ago = (datetime.now(timezone.utc) - timedelta(days=30)).strftime("%Y-%m-%d")
        logs = db.query(CarbonLog).filter(
            CarbonLog.user_id == user_id,
            CarbonLog.date >= thirty_days_ago
        ).all()

        highest_cat = "transportation"
        if logs:
            cat_totals = {}
            for log in logs:
                cat_totals[log.category] = cat_totals.get(log.category, 0) + log.co2_equivalent
            highest_cat = max(cat_totals, key=cat_totals.get)

        if genai and settings.GEMINI_API_KEY:
            try:
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                
                class GeminiChallengeList(BaseModel):
                    challenges: list[GeminiChallenge]

                prompt = (
                    f"Generate 3 weekly eco-challenges for a user whose highest carbon footprint category is '{highest_cat}'. "
                    "Provide 2 challenges from this highest category, and 1 challenge from another carbon category (like food, energy, waste, digital, or shopping). "
                    "Make sure the challenges are realistic, actionable, and fun. "
                    "Assign a reasonable experience points value (XP, between 30 and 150) and estimated CO2 savings in kg (between 0.5 and 25.0)."
                )

                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": GeminiChallengeList
                    }
                )
                if response and response.parsed:
                    return [
                        {
                            "title": ch.title,
                            "description": ch.description,
                            "xp": ch.xp,
                            "co2_saving": ch.co2_saving
                        }
                        for ch in response.parsed.challenges
                    ]
            except Exception as e:
                logger.error(f"Error calling Gemini in get_weekly_challenges: {e}")

        # Challenges database fallback
        challenges = {
            "transportation": [
                {"title": "Transit Trial", "description": "Take the metro or bus for 3 commutes instead of driving.", "xp": 80, "co2_saving": 12.5},
                {"title": "Eco-Pedaling", "description": "Walk or bike for all trips under 2 km this week.", "xp": 100, "co2_saving": 8.0},
                {"title": "Carpool Coordinator", "description": "Share a ride to work or event with a colleague.", "xp": 60, "co2_saving": 10.2}
            ],
            "energy": [
                {"title": "Vampire Slayer", "description": "Unplug all electronics and chargers not in use before bed.", "xp": 50, "co2_saving": 4.5},
                {"title": "Cold Clean", "description": "Wash all laundry cycles in cold water instead of hot.", "xp": 60, "co2_saving": 3.8},
                {"title": "Thermostat Tweak", "description": "Adjust your heating down 1 degree or cooling up 1 degree for the week.", "xp": 70, "co2_saving": 9.0}
            ],
            "food": [
                {"title": "Meatless Mondays", "description": "Prepare fully vegetarian meals for the entire day.", "xp": 60, "co2_saving": 6.4},
                {"title": "Go Vegan for 2 Days", "description": "Eat purely plant-based meals for 48 hours.", "xp": 100, "co2_saving": 14.2},
                {"title": "Zero Waste Chef", "description": "Throw away absolutely zero edible food leftovers this week.", "xp": 80, "co2_saving": 5.0}
            ],
            "waste": [
                {"title": "Sorting Champion", "description": "Clean and sort all plastics, papers, and glass for recycling.", "xp": 50, "co2_saving": 2.2},
                {"title": "Single-Use Strike", "description": "Refuse all single-use plastic cups, straws, and bags for 7 days.", "xp": 80, "co2_saving": 3.5},
                {"title": "Kitchen Composter", "description": "Compost all vegetable peels and organic coffee grounds.", "xp": 70, "co2_saving": 4.0}
            ],
            "shopping": [
                {"title": "Thrift Searcher", "description": "Buy a pre-owned clothing item instead of buying new.", "xp": 70, "co2_saving": 15.0},
                {"title": "No-Buy Challenge", "description": "Commit to buying zero non-essential items for 5 days.", "xp": 90, "co2_saving": 20.0}
            ],
            "digital": [
                {"title": "Digital Detox", "description": "Reduce screen streaming time by 2 hours daily and read a book.", "xp": 60, "co2_saving": 1.5},
                {"title": "Inbox Cleanse", "description": "Delete 100 old emails to clean server capacity storage.", "xp": 50, "co2_saving": 0.8}
            ]
        }

        # Select challenges. Pick 2 from the highest category and 1 random from other categories.
        selected = list(challenges.get(highest_cat, challenges["transportation"]))[:2]
        
        other_cats = [c for c in challenges.keys() if c != highest_cat]
        random_cat = random.choice(other_cats)
        selected.append(random.choice(challenges[random_cat]))

        return selected

    @staticmethod
    def generate_roadmap(db: Session, user_id: int) -> dict:
        """
        Creates a custom, multi-step carbon reduction roadmap for the user,
        calculating projected savings.
        If GEMINI_API_KEY is configured, it uses Gemini API structured output to generate personalized steps.
        """
        analysis = AIEngine.calculate_risk_and_goal_probability(db, user_id)
        risks = analysis.get("risk_behaviors", [])

        # Get user budget & carbon history summary for context
        profile = db.query(UserProfile).filter(UserProfile.user_id == user_id).first()
        budget = profile.carbon_budget if profile else 15.0

        thirty_days_ago = (datetime.now(timezone.utc) - timedelta(days=30)).strftime("%Y-%m-%d")
        logs = db.query(CarbonLog).filter(
            CarbonLog.user_id == user_id,
            CarbonLog.date >= thirty_days_ago
        ).all()

        history_summary = ""
        if logs:
            cat_totals = {}
            for log in logs:
                cat_totals[log.category] = cat_totals.get(log.category, 0) + log.co2_equivalent
            history_summary = ", ".join([f"{cat}: {val:.1f} kg CO2e" for cat, val in cat_totals.items()])
        else:
            history_summary = "No recent logging history."

        if genai and settings.GEMINI_API_KEY:
            try:
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                prompt = (
                    "Generate a custom, multi-step carbon reduction roadmap for a user. "
                    f"User daily carbon budget: {budget} kg CO2e.\n"
                    f"User recent 30-day carbon emissions summary: {history_summary}.\n"
                    f"Identified high-risk behaviors: {', '.join(risks)}.\n\n"
                    "Create a 4-phase pathway:\n"
                    "Phase 1: Immediate Wins (Week 1-2)\n"
                    "Phase 2: Household Adjustments (Month 1)\n"
                    "Phase 3: Systematic Upgrades (Month 3-6)\n"
                    "Phase 4: Structural Changes (Year 1+)\n"
                    "Each phase should contain 3 specific, highly tailored actions based on the user's risks. "
                    "Estimate the difficulty (Easy, Medium, Hard) and projected CO2 savings in kg for each phase."
                )

                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": GeminiRoadmap
                    }
                )
                if response and response.parsed:
                    roadmap_data = response.parsed
                    return {
                        "user_id": user_id,
                        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
                        "risk_analysis_context": risks,
                        "steps": [
                            {
                                "phase": step.phase,
                                "actions": step.actions,
                                "projected_co2_savings_kg": step.projected_co2_savings_kg,
                                "difficulty": step.difficulty
                            }
                            for step in roadmap_data.steps
                        ],
                        "total_projected_savings_annual_kg": roadmap_data.total_projected_savings_annual_kg
                    }
            except Exception as e:
                logger.error(f"Error calling Gemini in generate_roadmap: {e}")

        # Local fallback logic
        steps = [
            {
                "phase": "Phase 1: Immediate Wins (Week 1-2)",
                "actions": [
                    "Swap short car trips (<3 km) for walking or cycling.",
                    "Eat plant-based meals at least 2 days per week.",
                    "Unplug household standby appliances when not in use."
                ],
                "projected_co2_savings_kg": 25.0,
                "difficulty": "Easy"
            },
            {
                "phase": "Phase 2: Household Adjustments (Month 1)",
                "actions": [
                    "Transition all lightbulbs to Energy Star LEDs.",
                    "Ensure cold-wash settings are selected for laundry.",
                    "Start composting organic kitchen waste."
                ],
                "projected_co2_savings_kg": 60.0,
                "difficulty": "Medium"
            },
            {
                "phase": "Phase 3: Systematic Upgrades (Month 3-6)",
                "actions": [
                    "Upgrade to a smart programmable thermostat.",
                    "For unavoidable long commutes, purchase verified carbon offsets from the Marketplace.",
                    "Transition energy tariff to a 100% green renewable provider."
                ],
                "projected_co2_savings_kg": 180.0,
                "difficulty": "Medium"
            },
            {
                "phase": "Phase 4: Structural Lifestyle Changes (Year 1+)",
                "actions": [
                    "Upgrade your primary vehicle to a battery electric vehicle (EV).",
                    "Install rooftop solar panels or purchase community solar shares.",
                    "Transition heating source from gas to an electric heat pump."
                ],
                "projected_co2_savings_kg": 1200.0,
                "difficulty": "Hard"
            }
        ]

        total_savings = sum(step["projected_co2_savings_kg"] for step in steps)

        return {
            "user_id": user_id,
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
            "risk_analysis_context": risks,
            "steps": steps,
            "total_projected_savings_annual_kg": total_savings
        }

    @staticmethod
    def scan_carbon_image(image_base64: str) -> dict:
        """
        Uses Gemini 2.0 Multimodal capabilities to scan a receipt, utility bill, or food image,
        extract carbon log details, and format as structured output.
        """
        if genai and types and settings.GEMINI_API_KEY:
            try:
                # Strip base64 metadata header if present
                if "," in image_base64:
                    image_base64 = image_base64.split(",")[1]
                
                # Convert base64 to bytes
                image_bytes = base64.b64decode(image_base64)
                
                client = genai.Client(api_key=settings.GEMINI_API_KEY)
                
                # Call gemini with multimodal inline data
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=[
                        types.Part.from_bytes(
                            data=image_bytes,
                            mime_type="image/jpeg"
                        ),
                        (
                            "Analyze this image (which could be a utility bill, shopping receipt, meal, or transit ticket). "
                            "Extract the carbon-relevant activity and categorize it into one of these categories and subcategories:\n"
                            "- transportation: petrol_car, diesel_car, electric_car, motorcycle, metro, bus, short_flight, long_flight\n"
                            "- energy: electricity, gas, water\n"
                            "- food: beef, pork_poultry, dairy, vegetarian, vegan\n"
                            "- waste: landfill, recycled, composted\n"
                            "- shopping: clothing, electronics, misc\n"
                            "- digital: streaming, browsing, ai_query\n\n"
                            "Return the structured details including a numeric value (e.g. quantity of food in kg, electricity in kWh, price in USD, distance in km), "
                            "the correct unit, and a friendly explanation."
                        )
                    ],
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": GeminiScanResult
                    }
                )
                if response and response.parsed:
                    return {
                        "category": response.parsed.category,
                        "subcategory": response.parsed.subcategory,
                        "value": response.parsed.value,
                        "unit": response.parsed.unit,
                        "explanation": response.parsed.explanation
                    }
            except Exception as e:
                logger.error(f"Error calling Gemini in scan_carbon_image: {e}")
                
        # Mock fallback if no api key or error
        return {
            "category": "food",
            "subcategory": "vegan",
            "value": 1.5,
            "unit": "kg",
            "explanation": "Offline scanner fallback: Scanned photo detected a vegetarian/vegan meal (~1.5 kg of green salad and tofu)."
        }
