from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models import Achievement, OffsetProject, LearningPath, LearningLesson, User, UserProfile, DigitalTwinState
from app.auth.auth import get_password_hash
import logging

logger = logging.getLogger("carboeco")

async def seed_database(db: AsyncSession):
    # 1. Seed Achievements
    achievements = [
        {
            "name": "First Steps",
            "description": "Log your first carbon footprint activity.",
            "xp_reward": 100,
            "badge_code": "first_log"
        },
        {
            "name": "Transit Champion",
            "description": "Log 5 public transit journeys (metro, bus, or train).",
            "xp_reward": 150,
            "badge_code": "transit_master"
        },
        {
            "name": "Herbivore Hero",
            "description": "Log 5 plant-based or vegan meals.",
            "xp_reward": 150,
            "badge_code": "green_eater"
        },
        {
            "name": "Circular Warrior",
            "description": "Log 5 recycling or composting activities.",
            "xp_reward": 150,
            "badge_code": "zero_waste"
        },
        {
            "name": "Consistent Green",
            "description": "Maintain a 3-day active logging streak.",
            "xp_reward": 200,
            "badge_code": "streak_3"
        },
        {
            "name": "Eco Habitual",
            "description": "Maintain a 7-day active logging streak.",
            "xp_reward": 350,
            "badge_code": "streak_7"
        }
    ]

    for ach in achievements:
        stmt = select(Achievement).where(Achievement.badge_code == ach["badge_code"])
        res = await db.execute(stmt)
        exists = res.scalar_one_or_none()
        if not exists:
            db.add(Achievement(**ach))
            
    # 2. Seed Offset Projects with real registry credentials
    projects = [
        {
            "name": "Amazon Basin Forest Conservation",
            "description": "Preventing deforestation and protecting critical ecosystems in Brazil's Acre state.",
            "cost_per_ton": 15.0,
            "co2_offset": 50000.0,
            "image_url": "amazon_rainforest.png",
            "verified_by": "VCS (Verified Carbon Standard)",
            "registry_id": "VCS-984",
            "registry_link": "https://registry.verra.org/app/projectDetail/VCS/984"
        },
        {
            "name": "Rajasthan Wind Power Project",
            "description": "Displacing fossil fuel grid energy with clean wind turbine installations in India.",
            "cost_per_ton": 11.5,
            "co2_offset": 80000.0,
            "image_url": "wind_farm.png",
            "verified_by": "Gold Standard",
            "registry_id": "GS-731",
            "registry_link": "https://registry.goldstandard.org/projects/details/731"
        },
        {
            "name": "Clean Cookstoves & Water in Kenya",
            "description": "Providing high-efficiency cookstoves to communities, lowering firewood demands and charcoal soot.",
            "cost_per_ton": 18.0,
            "co2_offset": 25000.0,
            "image_url": "clean_cookstoves.png",
            "verified_by": "Gold Standard",
            "registry_id": "GS-2144",
            "registry_link": "https://registry.goldstandard.org/projects/details/2144"
        }
    ]

    for proj in projects:
        stmt = select(OffsetProject).where(OffsetProject.name == proj["name"])
        res = await db.execute(stmt)
        exists = res.scalar_one_or_none()
        if not exists:
            db.add(OffsetProject(**proj))

    # 3. Seed Educational Learning Paths & Lessons
    paths_data = [
        {
            "title": "Carbon Footprint Foundations",
            "description": "Learn the basics of greenhouse gases, global emissions targets, and carbon accounting.",
            "difficulty": "Beginner",
            "estimated_minutes": 15,
            "xp_reward": 150,
            "lessons": [
                {
                    "title": "What is Carbon Footprint?",
                    "content": (
                        "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) "
                        "generated by human actions. The global average carbon footprint is roughly 4.7 tons of CO2e per person. "
                        "To prevent planetary temperatures from rising beyond 1.5C over pre-industrial levels, the global annual "
                        "average needs to drop under 2.0 tons per person by 2050. Every activity from commuting to streaming contributes."
                    ),
                    "quiz_question": "What is the targeted global average carbon footprint per person by 2050 to avoid critical heating?",
                    "quiz_options": ["Under 2.0 tons", "Under 10.0 tons", "Exactly 5.0 tons", "No limit"],
                    "quiz_answer": "Under 2.0 tons",
                    "xp_reward": 50
                },
                {
                    "title": "Understanding CO2 equivalents (CO2e)",
                    "content": (
                        "Different greenhouse gases trap heat differently. Methane (CH4) is over 28 times more potent than carbon dioxide "
                        "(CO2) over a 100-year timescale, while nitrous oxide (N2O) is 265 times more potent. To simplify measurements, "
                        "all gases are converted to CO2 equivalents (CO2e), expressing the footprint in terms of the amount of CO2 that "
                        "would cause equal global warming."
                    ),
                    "quiz_question": "What does the abbreviation 'CO2e' stand for in carbon tracking?",
                    "quiz_options": ["Carbon Dioxide equivalent", "Carbon Oxygen emission", "Combined Organic elements", "Carbonic Energy standard"],
                    "quiz_answer": "Carbon Dioxide equivalent",
                    "xp_reward": 50
                }
            ]
        },
        {
            "title": "Sustainable Consumption & Diet",
            "description": "Understand the massive carbon impact of what you eat and consume.",
            "difficulty": "Intermediate",
            "estimated_minutes": 20,
            "xp_reward": 200,
            "lessons": [
                {
                    "title": "The Methane Footprint of Red Meat",
                    "content": (
                        "Animal agriculture contributes around 14.5% of all global greenhouse emissions. Ruminant animals like cows "
                        "and sheep produce methane through enteric fermentation during digestion. 1 kg of beef produces roughly "
                        "27 kg of CO2e, whereas 1 kg of tofu or vegetables produces under 1.5 kg. Swapping beef for beans or vegan "
                        "options twice a week decreases your dietary footprint by over 30%."
                    ),
                    "quiz_question": "Why is red meat (like beef) far more carbon-intensive than plant protein?",
                    "quiz_options": [
                        "Cows produce methane during digestion", 
                        "Vegetables are artificial and do not breathe", 
                        "Vegetables require heating to grow", 
                        "Red meat is processed using coal furnaces"
                    ],
                    "quiz_answer": "Cows produce methane during digestion",
                    "xp_reward": 50
                },
                {
                    "title": "Food Waste and Landfill Methane",
                    "content": (
                        "If food waste were a country, it would be the third-largest emitter in the world! When organic food waste is "
                        "sent to municipal landfills, it is compressed under layers of trash. Without oxygen, anaerobic bacteria "
                        "decompose the food, generating methane gas. Composting food waste allows aerobic decomposition, reducing "
                        "methane emissions substantially."
                    ),
                    "quiz_question": "What gas is produced when food waste decomposes anaerobically in a landfill?",
                    "quiz_options": ["Methane", "Oxygen", "Nitrogen", "Helium"],
                    "quiz_answer": "Methane",
                    "xp_reward": 50
                }
            ]
        }
    ]

    for p_data in paths_data:
        stmt = select(LearningPath).where(LearningPath.title == p_data["title"])
        res = await db.execute(stmt)
        exists = res.scalar_one_or_none()
        if not exists:
            lessons_list = p_data.pop("lessons")
            path = LearningPath(**p_data)
            db.add(path)
            await db.flush()
            
            for l_data in lessons_list:
                db.add(LearningLesson(path_id=path.id, **l_data))

    # 4. Seed Leaderboard Mock Users (so the leaderboard is populated)
    mock_users = [
        {"email": "alice@carboeco.org", "name": "EcoAlice", "xp": 1820, "level": 4, "streak": 12, "region": "US"},
        {"email": "bob@carboeco.org", "name": "GreenBob", "xp": 1250, "level": 3, "streak": 7, "region": "IN"},
        {"email": "charlie@carboeco.org", "name": "SustainCharlie", "xp": 610, "level": 2, "streak": 3, "region": "EU"}
    ]

    for mu in mock_users:
        stmt = select(User).where(User.email == mu["email"])
        res = await db.execute(stmt)
        exists = res.scalar_one_or_none()
        if not exists:
            pwd_hash = get_password_hash("mockpassword123")
            user = User(email=mu["email"], password_hash=pwd_hash, role="user", is_active=True)
            db.add(user)
            await db.flush()

            profile = UserProfile(
                user_id=user.id,
                full_name=mu["name"],
                avatar="avatar_2.png" if "Bob" in mu["name"] else "avatar_3.png",
                xp=mu["xp"],
                level=mu["level"],
                streak_count=mu["streak"],
                last_active_date=None,
                carbon_budget=15.0,
                region=mu["region"]
            )
            db.add(profile)
            
            twin = DigitalTwinState(
                user_id=user.id,
                tree_growth_stage=mu["level"],
                energy_efficiency_score=85.0 if mu["streak"] > 5 else 60.0,
                current_avatar_state_json={
                    "health": 90,
                    "theme": "emerald" if mu["streak"] > 5 else "sky",
                    "leaves_color": "#10B981" if mu["streak"] > 5 else "#0EA5E9",
                    "accessories": []
                }
            )
            db.add(twin)

    try:
        await db.commit()
        logger.info("Successfully seeded database with achievements, offset projects, and education courses.")
    except Exception as e:
        await db.rollback()
        logger.error(f"Error seeding database: {e}")
